// Frontend_Sanjay_Gupta/handson_08/src/App.vue
<template>
  <div class="app-container">
    <Header />
    
    <main>
      <RouterView />
    </main>

    <footer>
      <div class="footer-content">
        <p>&copy; 2026 Student Portal. All rights reserved.</p>
        <div class="footer-links">
          <a href="#">Privacy Policy</a>
          <a href="#">Terms of Service</a>
          <a href="#">Contact Support</a>
        </div>
      </div>
    </footer>
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router'
import Header from './components/Header.vue'
</script>

<style scoped>
</style>

// Frontend_Sanjay_Gupta/handson_07/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'handson_07';
}

<div class="app-container">
  <app-header></app-header>
  
  <main>
    <router-outlet></router-outlet>
  </main>

  <footer>
    <div class="footer-content">
      <p>&copy; 2026 Student Portal. All rights reserved.</p>
      <div class="footer-links">
        <a href="#">Privacy Policy</a>
        <a href="#">Terms of Service</a>
        <a href="#">Contact Support</a>
      </div>
    </div>
  </footer>
</div>
