// Frontend_Sanjay_Gupta/handson_05/src/components/CourseCard.jsx
import React from 'react';

function CourseCard({ id, name, code, credits, grade, description, onEnroll, isEnrolled }) {
  return (
    <article className="course-card">
      <div className="course-header">
        <h3>{name}</h3>
        <span className="course-tag">{code}</span>
      </div>
      <p>{description}</p>
      <div className="course-footer" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%', marginTop: 'auto' }}>
        <span className="credits">Credits: {credits}</span>
        <button
          type="button"
          className="btn-primary"
          onClick={onEnroll}
          disabled={isEnrolled}
          style={
            isEnrolled
              ? { backgroundColor: '#cbd5e1', color: '#64748b', border: '1px solid #cbd5e1', cursor: 'not-allowed', padding: '0.4rem 1rem', fontSize: '0.8rem' }
              : { padding: '0.4rem 1rem', fontSize: '0.8rem' }
          }
        >
          {isEnrolled ? 'Enrolled' : 'Enroll'}
        </button>
      </div>
    </article>
  );
}

export default CourseCard;

// Frontend_Sanjay_Gupta/handson_08/src/components/CourseCard.vue
<template>
  <article class="course-card">
    <div class="course-header">
      <h3>{{ name }}</h3>
      <span class="course-tag">{{ code }}</span>
    </div>
    <p>{{ description }}</p>
    <div class="course-footer" style="display: flex; justify-content: space-between; align-items: center; width: 100%; margin-top: auto; gap: 0.5rem;">
      <span class="credits">Credits: {{ credits }}</span>
      <span style="font-size: 0.75rem; font-weight: 500; background-color: #f1f5f9; color: #475569; padding: 0.25rem 0.5rem; border-radius: 4px; border: 1px solid var(--border-subtle);">Grade: {{ grade }}</span>
    </div>
  </article>
</template>

<script setup>
defineProps({
  name: {
    type: String,
    required: true
  },
  code: {
    type: String,
    required: true
  },
  credits: {
    type: Number,
    required: true
  },
  grade: {
    type: String,
    required: true
  },
  description: {
    type: String,
    default: ''
  }
})
</script>

<style scoped>
</style>
