// Frontend_Sanjay_Gupta/handson_10/src/components/Header.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { useSelector } from 'react-redux';

function Header(props) {
  const enrolledCourses = useSelector((state) => state.enrollment.enrolledCourses);

  return (
    <header>
      <div className="logo">
        <span className="logo-icon">🎓</span>
        <span className="logo-text">{props.siteName || "Student Portal"}</span>
      </div>
      <div className="hamburger">☰</div>
      <nav>
        <ul>
          <li>
            <NavLink to="/" end className={({ isActive }) => (isActive ? 'active' : '')}>
              Home
            </NavLink>
          </li>
          <li>
            <NavLink to="/courses" className={({ isActive }) => (isActive ? 'active' : '')}>
              Courses
            </NavLink>
          </li>
          <li>
            <NavLink to="/profile" className={({ isActive }) => (isActive ? 'active' : '')}>
              Profile
            </NavLink>
          </li>
          {enrolledCourses.length > 0 && (
            <li className="enrolled-indicator">
              <span className="enrolled-badge">Enrolled: {enrolledCourses.length}</span>
            </li>
          )}
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// Frontend_Sanjay_Gupta/handson_08/src/components/Header.vue
<template>
  <header>
    <div class="logo">
      <span class="logo-icon">🎓</span>
      <span class="logo-text">Student Portal</span>
    </div>
    <div class="hamburger">☰</div>
    <nav>
      <ul>
        <li><RouterLink to="/" active-class="active" exact-active-class="active">Home</RouterLink></li>
        <li><RouterLink to="/courses" active-class="active">Courses</RouterLink></li>
        <li>
          <RouterLink to="/profile" active-class="active">
            Profile
            <span v-if="store.enrolledCourses.length > 0" class="badge" style="background-color: var(--accent-color); color: #ffffff; padding: 0.1rem 0.4rem; font-size: 0.75rem; border-radius: 10px; margin-left: 0.25rem;">
              {{ store.enrolledCourses.length }}
            </span>
          </RouterLink>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
</style>
