// Frontend_Sanjay_Gupta/handson_05/src/components/StudentProfile.jsx
import React, { useState } from 'react';

function StudentProfile() {
  const [profile, setProfile] = useState({
    name: 'Sanjay Gupta',
    email: 'sanjay.gupta@example.com',
    semester: '6'
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setProfile((prevProfile) => ({
      ...prevProfile,
      [name]: value
    }));
  };

  return (
    <section id="profile" style={{ padding: '2.5rem 0', borderTop: '1px solid var(--border-subtle)' }}>
      <div className="section-header">
        <h2>Student Profile</h2>
        <div className="section-underline"></div>
      </div>
      <form 
        style={{ 
          maxWidth: '500px', 
          margin: '0 auto', 
          backgroundColor: 'var(--bg-white)', 
          padding: '2rem', 
          borderRadius: '8px', 
          border: '1px solid var(--border-subtle)', 
          boxShadow: '0 2px 4px rgba(0,0,0,0.02)' 
        }}
        onSubmit={(e) => e.preventDefault()}
      >
        <div style={{ marginBottom: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.5rem', textAlign: 'left' }}>
          <label style={{ fontSize: '0.9rem', fontWeight: '600', color: 'var(--text-dark)' }}>Name</label>
          <input
            type="text"
            name="name"
            value={profile.name}
            onChange={handleChange}
            style={{ padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)', fontSize: '0.95rem' }}
          />
        </div>
        <div style={{ marginBottom: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.5rem', textAlign: 'left' }}>
          <label style={{ fontSize: '0.9rem', fontWeight: '600', color: 'var(--text-dark)' }}>Email</label>
          <input
            type="email"
            name="email"
            value={profile.email}
            onChange={handleChange}
            style={{ padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)', fontSize: '0.95rem' }}
          />
        </div>
        <div style={{ marginBottom: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.5rem', textAlign: 'left' }}>
          <label style={{ fontSize: '0.9rem', fontWeight: '600', color: 'var(--text-dark)' }}>Semester</label>
          <input
            type="number"
            name="semester"
            value={profile.semester}
            onChange={handleChange}
            style={{ padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)', fontSize: '0.95rem' }}
          />
        </div>
        <div 
          style={{ 
            marginTop: '1.5rem', 
            padding: '0.75rem', 
            backgroundColor: 'var(--accent-light)', 
            border: '1px dashed rgba(29, 78, 216, 0.3)', 
            borderRadius: '6px', 
            fontSize: '0.9rem', 
            color: 'var(--accent-color)', 
            fontWeight: '500', 
            textAlign: 'center' 
          }}
        >
          State Live Preview: {profile.name} ({profile.email}) - Semester {profile.semester}
        </div>
      </form>
    </section>
  );
}

export default StudentProfile;

// Frontend_Sanjay_Gupta/handson_07/src/app/components/student-profile/student-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-student-profile',
  templateUrl: './student-profile.component.html',
  styleUrl: './student-profile.component.css'
})
export class StudentProfileComponent implements OnInit {
  profileForm!: FormGroup;

  ngOnInit(): void {
    this.profileForm = new FormGroup({
      name: new FormControl('Sanjay Gupta', [Validators.required]),
      email: new FormControl('sanjay.gupta@example.com', [Validators.required, Validators.email]),
      semester: new FormControl(6, [
        Validators.required,
        Validators.min(1),
        Validators.max(8)
      ])
    });
  }

  onSubmit(): void {
    if (this.profileForm.valid) {
      console.log('Form Submitted!', this.profileForm.value);
    }
  }

  // Helper getters to check control validation in template markup
  get name() {
    return this.profileForm.get('name');
  }

  get email() {
    return this.profileForm.get('email');
  }

  get semester() {
    return this.profileForm.get('semester');
  }
}

<section id="profile" style="padding: 2.5rem 0;">
  <div class="section-header">
    <h2>Student Profile</h2>
    <div class="section-underline"></div>
  </div>
  <form 
    style="max-width: 500px; margin: 0 auto; background-color: var(--bg-white); padding: 2rem; border-radius: 8px; border: 1px solid var(--border-subtle); box-shadow: 0 2px 4px rgba(0,0,0,0.02)"
    [formGroup]="profileForm"
    (ngSubmit)="onSubmit()"
  >
    <div style="margin-bottom: 1.25rem; display: flex; flex-direction: column; gap: 0.5rem; text-align: left;">
      <label style="font-size: 0.9rem; font-weight: 600; color: var(--text-dark);">Name</label>
      <input
        type="text"
        formControlName="name"
        style="padding: 0.75rem; border-radius: 6px; border: 1px solid var(--border-color); font-size: 0.95rem; width: 100%; box-sizing: border-box;"
      />
      <div *ngIf="name?.invalid && (name?.dirty || name?.touched)" style="color: #ef4444; font-size: 0.8rem; font-weight: 500; margin-top: 0.25rem;">
        Name is required
      </div>
    </div>
    
    <div style="margin-bottom: 1.25rem; display: flex; flex-direction: column; gap: 0.5rem; text-align: left;">
      <label style="font-size: 0.9rem; font-weight: 600; color: var(--text-dark);">Email</label>
      <input
        type="email"
        formControlName="email"
        style="padding: 0.75rem; border-radius: 6px; border: 1px solid var(--border-color); font-size: 0.95rem; width: 100%; box-sizing: border-box;"
      />
      <div *ngIf="email?.invalid && (email?.dirty || email?.touched)" style="color: #ef4444; font-size: 0.8rem; font-weight: 500; margin-top: 0.25rem;">
        <span *ngIf="email?.errors?.['required']">Email is required</span>
        <span *ngIf="email?.errors?.['email']">Enter a valid email</span>
      </div>
    </div>
    
    <div style="margin-bottom: 1.25rem; display: flex; flex-direction: column; gap: 0.5rem; text-align: left;">
      <label style="font-size: 0.9rem; font-weight: 600; color: var(--text-dark);">Semester</label>
      <input
        type="number"
        formControlName="semester"
        style="padding: 0.75rem; border-radius: 6px; border: 1px solid var(--border-color); font-size: 0.95rem; width: 100%; box-sizing: border-box;"
      />
      <div *ngIf="semester?.invalid && (semester?.dirty || semester?.touched)" style="color: #ef4444; font-size: 0.8rem; font-weight: 500; margin-top: 0.25rem;">
        <span *ngIf="semester?.errors?.['required']">Semester is required</span>
        <span *ngIf="semester?.errors?.['min'] || semester?.errors?.['max']">Semester must be between 1 and 8</span>
      </div>
    </div>
    
    <div style="margin-top: 1.5rem; display: flex; flex-direction: column; gap: 1.25rem; align-items: center;">
      <button 
        type="submit" 
        class="btn-primary" 
        [disabled]="profileForm.invalid" 
        style="width: 100%; padding: 0.75rem;"
        [style.opacity]="profileForm.invalid ? '0.5' : '1'"
        [style.cursor]="profileForm.invalid ? 'not-allowed' : 'pointer'"
      >
        Submit
      </button>

      <div 
        style="width: 100%; padding: 0.75rem; background-color: var(--accent-light); border: 1px dashed rgba(29, 78, 216, 0.3); border-radius: 6px; font-size: 0.9rem; color: var(--accent-color); font-weight: 500; text-align: center; box-sizing: border-box;"
      >
        State Live Preview: {{ profileForm.value.name }} ({{ profileForm.value.email }}) - Semester {{ profileForm.value.semester }}
      </div>
    </div>
  </form>
</section>
